# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alex/learning/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(384, 88)
        Dialog.setMinimumSize(QtCore.QSize(384, 88))
        Dialog.setMaximumSize(QtCore.QSize(384, 88))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lblMessage = QtWidgets.QLabel(Dialog)
        self.lblMessage.setGeometry(QtCore.QRect(20, 20, 251, 51))
        self.lblMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblMessage.setObjectName("lblMessage")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.close) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.lblMessage.setText(_translate("Dialog", "Question"))
import res_rc
