# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\learning\home.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(981, 663)
        Home.setMinimumSize(QtCore.QSize(588, 413))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Home.setFont(font)
        Home.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tab1 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab1.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab1.setMovable(False)
        self.tab1.setObjectName("tab1")
        self.tabLED = QtWidgets.QWidget()
        self.tabLED.setObjectName("tabLED")
        self.btnLEDOn = QtWidgets.QPushButton(self.tabLED)
        self.btnLEDOn.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.btnLEDOn.setMouseTracking(False)
        self.btnLEDOn.setAcceptDrops(False)
        self.btnLEDOn.setAutoFillBackground(False)
        self.btnLEDOn.setStyleSheet("background-color: rgb(143, 255, 190);\n"
"selection-background-color: rgb(170, 85, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLEDOn.setIcon(icon)
        self.btnLEDOn.setAutoDefault(False)
        self.btnLEDOn.setDefault(False)
        self.btnLEDOn.setFlat(False)
        self.btnLEDOn.setObjectName("btnLEDOn")
        self.btnLEDOff = QtWidgets.QPushButton(self.tabLED)
        self.btnLEDOff.setGeometry(QtCore.QRect(30, 70, 61, 31))
        self.btnLEDOff.setAcceptDrops(False)
        self.btnLEDOff.setAutoFillBackground(False)
        self.btnLEDOff.setStyleSheet("background-color: rgb(143, 255, 190);\n"
"background-color: rgb(195, 69, 69);")
        self.btnLEDOff.setIcon(icon)
        self.btnLEDOff.setAutoDefault(False)
        self.btnLEDOff.setDefault(False)
        self.btnLEDOff.setFlat(False)
        self.btnLEDOff.setObjectName("btnLEDOff")
        self.tab1.addTab(self.tabLED, "")
        self.tabCtl = QtWidgets.QWidget()
        self.tabCtl.setObjectName("tabCtl")
        self.dial1 = QtWidgets.QDial(self.tabCtl)
        self.dial1.setGeometry(QtCore.QRect(9, 9, 100, 100))
        self.dial1.setMinimumSize(QtCore.QSize(41, 41))
        self.dial1.setAutoFillBackground(False)
        self.dial1.setTracking(False)
        self.dial1.setOrientation(QtCore.Qt.Vertical)
        self.dial1.setInvertedAppearance(False)
        self.dial1.setInvertedControls(False)
        self.dial1.setWrapping(False)
        self.dial1.setNotchesVisible(True)
        self.dial1.setObjectName("dial1")
        self.comboBox = QtWidgets.QComboBox(self.tabCtl)
        self.comboBox.setGeometry(QtCore.QRect(110, 30, 75, 18))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.axWidget = QAxContainer.QAxWidget(self.tabCtl)
        self.axWidget.setProperty("geometry", QtCore.QRect(20, 120, 80, 70))
        self.axWidget.setObjectName("axWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabCtl)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 70, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.content_plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.content_plot.setContentsMargins(0, 0, 0, 0)
        self.content_plot.setObjectName("content_plot")
        self.tab1.addTab(self.tabCtl, "")
        self.gridLayout_2.addWidget(self.tab1, 0, 0, 1, 1)
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuFile.setIcon(icon1)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuView.setIcon(icon2)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuHelp.setIcon(icon3)
        self.menuHelp.setObjectName("menuHelp")
        Home.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(Home)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/alert round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(Home)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/open folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Home)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(Home)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/alert triangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon7)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Home)
        self.tab1.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        self.btnLEDOn.setToolTip(_translate("Home", "Turn on LED lights"))
        self.btnLEDOn.setText(_translate("Home", "ON"))
        self.btnLEDOff.setToolTip(_translate("Home", "Turn off LED lights"))
        self.btnLEDOff.setText(_translate("Home", "OFF"))
        self.tab1.setTabText(self.tab1.indexOf(self.tabLED), _translate("Home", "LED"))
        self.comboBox.setItemText(0, _translate("Home", "gasdkjakl"))
        self.comboBox.setItemText(1, _translate("Home", "gsagag"))
        self.comboBox.setItemText(2, _translate("Home", "ahhf"))
        self.comboBox.setItemText(3, _translate("Home", "hfdah"))
        self.comboBox.setItemText(4, _translate("Home", "ah"))
        self.comboBox.setItemText(5, _translate("Home", "ahfdh"))
        self.comboBox.setItemText(6, _translate("Home", "ah"))
        self.tab1.setTabText(self.tab1.indexOf(self.tabCtl), _translate("Home", "Controls"))
        self.menuFile.setTitle(_translate("Home", "File"))
        self.menuView.setTitle(_translate("Home", "View"))
        self.menuHelp.setTitle(_translate("Home", "Help"))
        self.actionAbout.setText(_translate("Home", "About"))
        self.actionOpen.setText(_translate("Home", "Open"))
        self.actionSave.setText(_translate("Home", "Save"))
        self.actionQuit.setText(_translate("Home", "Quit"))
from PyQt5 import QAxContainer
import res
