# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\Learning\home.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(588, 413)
        Home.setMinimumSize(QtCore.QSize(588, 413))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Home.setFont(font)
        Home.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 591, 391))
        self.tabWidget.setStyleSheet("background-color: rgb(50, 150, 150);")
        self.tabWidget.setObjectName("tabWidget")
        self.tabLED = QtWidgets.QWidget()
        self.tabLED.setObjectName("tabLED")
        self.btnLEDOn = QtWidgets.QPushButton(self.tabLED)
        self.btnLEDOn.setGeometry(QtCore.QRect(30, 30, 61, 31))
        self.btnLEDOn.setMouseTracking(False)
        self.btnLEDOn.setAcceptDrops(False)
        self.btnLEDOn.setAutoFillBackground(False)
        self.btnLEDOn.setStyleSheet("background-color: rgb(143, 255, 190);\n"
"selection-background-color: rgb(170, 85, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLEDOn.setIcon(icon)
        self.btnLEDOn.setAutoDefault(False)
        self.btnLEDOn.setDefault(False)
        self.btnLEDOn.setFlat(False)
        self.btnLEDOn.setObjectName("btnLEDOn")
        self.btnLEDOff = QtWidgets.QPushButton(self.tabLED)
        self.btnLEDOff.setGeometry(QtCore.QRect(30, 70, 61, 31))
        self.btnLEDOff.setAcceptDrops(False)
        self.btnLEDOff.setAutoFillBackground(False)
        self.btnLEDOff.setStyleSheet("background-color: rgb(143, 255, 190);\n"
"background-color: rgb(195, 69, 69);")
        self.btnLEDOff.setIcon(icon)
        self.btnLEDOff.setAutoDefault(False)
        self.btnLEDOff.setDefault(False)
        self.btnLEDOff.setFlat(False)
        self.btnLEDOff.setObjectName("btnLEDOff")
        self.tabWidget.addTab(self.tabLED, "")
        self.tabCtl = QtWidgets.QWidget()
        self.tabCtl.setObjectName("tabCtl")
        self.dial = QtWidgets.QDial(self.tabCtl)
        self.dial.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.dial.setMinimumSize(QtCore.QSize(71, 71))
        self.dial.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-color: rgb(85, 170, 127);")
        self.dial.setTracking(False)
        self.dial.setInvertedAppearance(False)
        self.dial.setInvertedControls(False)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(False)
        self.dial.setObjectName("dial")
        self.tabWidget.addTab(self.tabCtl, "")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Home.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(Home)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/speech.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(Home)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/main/open folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Home)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/main/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(Home)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/main/alert round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Home)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Learning Qt"))
        self.btnLEDOn.setToolTip(_translate("Home", "Turn on LED lights"))
        self.btnLEDOn.setText(_translate("Home", "ON"))
        self.btnLEDOff.setToolTip(_translate("Home", "Turn off LED lights\n"
""))
        self.btnLEDOff.setText(_translate("Home", "OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLED), _translate("Home", "LED"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCtl), _translate("Home", "Controls"))
        self.menuFile.setTitle(_translate("Home", "File"))
        self.menuView.setTitle(_translate("Home", "View"))
        self.menuHelp.setTitle(_translate("Home", "Help"))
        self.actionAbout.setText(_translate("Home", "About"))
        self.actionOpen.setText(_translate("Home", "Open"))
        self.actionSave.setText(_translate("Home", "Save"))
        self.actionQuit.setText(_translate("Home", "Quit"))
import icons_rc
